services:
  metabase:
    extends:
      file: compose-base.yml
      service: base_service
    image: metabase/metabase:latest
    hostname: "${METABASE_HOST:-metabase}"
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - "$METABASE_PORT:$METABASE_PORT"
    environment:
      METABASE_DB_TYPE: $METABASE_DB_TYPE
      METABASE_DB_HOST: $POSTGRES_HOST
      METABASE_DB_PORT: $POSTGRES_PORT
      METABASE_DB_DBNAME: $METABASE_DB_DBNAME
      METABASE_DB_USER: $METABASE_DB_USER
      METABASE_DB_PASS: $METABASE_DB_PASS
    healthcheck:
      test: curl --fail -I http://localhost:$METABASE_PORT/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5