version: '3'
services:
  postgres:
    extends:
      file: compose-base.yml
      service: base_service
    image: postgres:latest
    hostname: "${PG_HOST}"
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: -p ${PG_PORT}