services:
  postgres:
    extends:
      file: compose-base.yml
      service: base_service
    image: postgres:latest
    hostname: "${POSTGRES_HOST}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "${APP_DB}"
      POSTGRES_USER: "${APP_DB_USER}"
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_pass
      # POSTGRES_INITDB_ARGS: "--debug"
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -p ${POSTGRES_PORT} -d ${APP_DB} -U ${APP_DB_USER}
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 12
    secrets:
      - app_db_pass
