services:
  postgres:
    extends:
      file: compose-base.yml
      service: base_service
    image: postgres:latest
    hostname: "${POSTGRES_HOST}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data