services:
  ronin:
    extends:
      file: compose-base.yml
      service: base_service
    build: ./ronin
    ports:
      - "${RONIN_HEALTH_PORT}:${RONIN_HEALTH_PORT}"
    volumes:
      - ./ronin:/app  # Mount your local code into the container
      - ./data:/data
    secrets:
      - app_db_pass
      - metabase_db_pass
    # develop:
    #   watch:
    #     - path: ./ronin
    #       action: sync+restart
    #       target: /app
