version: '3'
services:
  metabase:
    extends:
      file: compose-metabase.yml
      service: metabase
    container_name: metabase
    networks:
      - metanet1
  postgres:
    extends:
      file: compose-postgres.yml
      service: postgres
    container_name: postgres
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge