services:
  postgres:
    extends:
      file: compose-postgres.yml
      service: postgres
    container_name: postgres
    networks:
      - metanet1
  spark:
    extends:
      file: compose-spark.yml
      service: spark
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
secrets:
  app_db_pass:
    file: secrets/app_db_pass.txt
  metabase_db_pass:
    file: secrets/metabase_db_pass.txta 