services:
  postgres:
    extends:
      file: compose-postgres.yml
      service: postgres
    container_name: postgres
    networks:
      - metanet1
  ronin:
    extends:
      file: compose-python.yml
      service: ronin
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge