services:
  metabase:
    depends_on:
      ronin:
        condition: service_healthy
        restart: true
      postgres:
        condition: service_started
    extends:
      file: compose-metabase.yml
      service: metabase
    container_name: metabase
    networks:
      - metanet1
  postgres:
    extends:
      file: compose-postgres.yml
      service: postgres
    container_name: postgres
    networks:
      - metanet1
  ronin:
    depends_on:
      - postgres
    extends:
      file: compose-python.yml
      service: ronin
    container_name: ronin
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge